name: TechTrends - Package with Docker

on:
  push:
    branches:
      - 'main'

jobs:
  package-with-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        context: project/techtrends
        push: true
        tags: techtrends:latest
